In [28]:
import numpy as np

In [29]:
x=[1,2,3,4]

In [30]:
type(x)

list

In [138]:
y=np.array([1,2,3,4])
print(y)

[1 2 3 4]


In [33]:
import numpy as np

In [35]:
array= np.zeros(5)

In [36]:
print(array)

[0. 0. 0. 0. 0.]


In [37]:
x=0
y=10
num=5

In [38]:
arr=np.ones(x)

In [39]:
print(arr)

[]


In [40]:
arr=np.arange(x)

In [41]:
print(arr)

[]


In [42]:
arr=np.linspace(x,y,num)

In [43]:
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [44]:
arr=np.add(x,y)

In [45]:
print(arr)

10


In [46]:
arr=np.subtract(x,y)

In [47]:
print(arr)

-10


In [48]:
arr=np.multiply(y,num)

In [49]:
print(arr)

50


In [50]:
arr=np.divide(x,y)

In [51]:
print(arr)

0.0


In [52]:
a=90.7
b=60
c=30
d=0

In [53]:
arr=np.sin(a)

In [54]:
print(arr)

0.3951094149183201


In [55]:
arr=np.cos(a)

In [56]:
print(arr)

-0.9186340676476693


In [57]:
arr=np.tan(c)

In [58]:
print(arr)

-6.405331196646276


In [59]:
arr=np.floor(a)

In [60]:
print(arr)

90.0


In [61]:
arr==np.ceil(a)

np.False_

In [62]:
print(arr)

90.0


In [63]:
arr=np.around(a)

In [64]:
print(arr)

91.0


In [65]:
arr=np.mean(num)

In [66]:
print(arr)

5.0


In [67]:
g=[1,2,3,4]
h=[5,6,4,3]

In [68]:
arr=np.mean(h)

In [70]:
print(arr)

4.5


In [71]:
arr=np.median(h)

In [72]:
print(arr)

4.5


In [73]:
arr=np.std(g)

In [74]:
print(arr)

1.118033988749895


In [75]:
arr=np.sum(g)

In [76]:
print(arr)

10


In [77]:
arr=np.min(h)

In [78]:
print(arr)

3


In [79]:
arr=np.max(h)

In [80]:
print(arr)

6


In [81]:
r=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]

In [82]:
arr=np.array(r)

In [83]:
newarr=np.reshape(2,1)

In [84]:
print(newarr)

[2]


In [85]:
arr=np.vstack(g)

In [86]:
print(arr)

[[1]
 [2]
 [3]
 [4]]


In [87]:
arr=np.hstack(h)

In [88]:
print(arr)

[5 6 4 3]


In [89]:
import numpy as np

In [13]:
x=5
y=8
z=10

In [15]:
arr=np.zeros(x)

In [17]:
print(arr)

[0. 0. 0. 0. 0.]


In [18]:
arr=np.eye(x,y)

In [22]:
print(arr)

[8 8 8 8 8]


In [20]:
print(arr)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]


In [21]:
arr=np.full(x,y)

In [27]:
print(arr)

[1. 1. 1. 1. 1.]


In [25]:
arr=np.empty(x)

In [26]:
print(arr)

[1. 1. 1. 1. 1.]


In [97]:
import numpy as np

In [100]:
arr = np.array([5,6,3,8])

In [101]:
print(np.sort(arr))

[3 5 6 8]


In [102]:
arr=np.array([1,2,3,3,5,3,6])

In [103]:
newarr=np.where(arr==3)

In [104]:
print(newarr)

(array([2, 3, 5]),)


In [105]:
arr=np.array([2,3,4,5])

In [108]:
newarr=np.searchsorted(arr,3)

In [109]:
print(newarr)

1


In [111]:
arr=np.array([[1,2,3,4],[5,6,7,8]])

In [113]:
print(arr.shape)

(2, 4)


In [114]:
arr=np.array([1,2,3,4,6])

In [115]:
x=arr.copy()

In [116]:
arr[0]=45

In [117]:
print(arr)
print(x)

[45  2  3  4  6]
[1 2 3 4 6]


In [118]:
arr=np.array([1,2,3,4,6])

In [119]:
x=arr.view()

In [121]:
arr[0]=45

In [122]:
print(arr)
print(x)

[45  2  3  4  6]
[45  2  3  4  6]


In [123]:
arr=np.array([1,2,3,4,5,6,7])

In [124]:
x=arr.copy()
y=arr.view()

In [125]:
print(x.base)
print(y.base)

None
[1 2 3 4 5 6 7]


In [129]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [133]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)


[[[1 4]
  [2 5]
  [3 6]]]


In [134]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])


In [135]:
newarr=np.array_split(arr,3)

In [136]:
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
